import { useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, Lock, Shield, Clock, CheckCircle, Copy, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { Incident } from '@/hooks/useIncidentStore';
import { useToast } from '@/hooks/use-toast';

interface Props {
  incident: Incident | null;
}

function formatDate(date: Date): string {
  return date.toLocaleString('en-US', {
    year: 'numeric', month: 'short', day: '2-digit',
    hour: '2-digit', minute: '2-digit', second: '2-digit',
    hour12: false,
  });
}

export function ReportPanel({ incident }: Props) {
  const { toast } = useToast();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isLocked, setIsLocked] = useState(false);

  if (!incident) {
    return (
      <div className="rounded-md border border-border bg-card p-8 h-full flex flex-col items-center justify-center">
        <FileText className="h-12 w-12 text-muted-foreground/30 mb-4" />
        <p className="text-sm text-muted-foreground">Select an incident to generate a report</p>
      </div>
    );
  }

  const handleDownload = () => {
    setIsGenerating(true);
    setTimeout(() => {
      const reportContent = [
        '═══════════════════════════════════════════════',
        '       BLACKBOX AI — INCIDENT REPORT',
        '═══════════════════════════════════════════════',
        '',
        `Report ID: RPT-${incident.id.toUpperCase()}`,
        `Generated: ${formatDate(new Date())}`,
        `Status: ${isLocked ? 'LOCKED — TAMPER-PROOF' : 'DRAFT'}`,
        '',
        '───────────────────────────────────────────────',
        'INCIDENT DETAILS',
        '───────────────────────────────────────────────',
        `Title: ${incident.title}`,
        `Timestamp: ${formatDate(incident.timestamp)}`,
        `Duration: ${incident.duration}`,
        `Status: ${incident.status.toUpperCase()}`,
        '',
        '───────────────────────────────────────────────',
        'ROOT CAUSE',
        '───────────────────────────────────────────────',
        incident.rootCause,
        '',
        '───────────────────────────────────────────────',
        'TECHNICAL ANALYSIS',
        '───────────────────────────────────────────────',
        incident.technicalExplanation,
        '',
        '───────────────────────────────────────────────',
        'CONTRIBUTING FACTORS',
        '───────────────────────────────────────────────',
        ...incident.contributingFactors.map((f, i) => `  ${i + 1}. ${f}`),
        '',
        '───────────────────────────────────────────────',
        'EVENT TIMELINE',
        '───────────────────────────────────────────────',
        ...incident.timeline.map(e => `  [${e.severity.toUpperCase().padEnd(8)}] ${formatDate(e.timestamp)} — ${e.label}: ${e.detail}`),
        '',
        '───────────────────────────────────────────────',
        'EVIDENCE SUMMARY',
        '───────────────────────────────────────────────',
        ...incident.evidence.map(e => `  [${e.type.toUpperCase().padEnd(13)}] ${e.label} (${e.unit}) — ${e.description}`),
        '',
        '═══════════════════════════════════════════════',
        `Hash: SHA256-${Math.random().toString(36).substring(2, 18).toUpperCase()}`,
        'Generated by BlackBox AI v3.2.1 — On-Device Processing',
        '═══════════════════════════════════════════════',
      ].join('\n');

      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `blackbox-report-${incident.id}.txt`;
      a.click();
      URL.revokeObjectURL(url);
      setIsGenerating(false);
      toast({ title: 'Report downloaded', description: `Incident report for ${incident.id} saved.` });
    }, 1500);
  };

  const handleCopy = () => {
    const summary = `BLACKBOX AI REPORT\n\n${incident.title}\n\nRoot Cause: ${incident.rootCause}\n\nTimeline:\n${incident.timeline.map(e => `- ${e.label}: ${e.detail}`).join('\n')}`;
    navigator.clipboard.writeText(summary);
    toast({ title: 'Copied to clipboard', description: 'Report summary copied.' });
  };

  const handleLock = () => {
    setIsLocked(true);
    toast({ title: 'Report locked', description: 'Tamper-proof seal applied. This report cannot be modified.' });
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="rounded-md border border-border bg-card p-4 h-full flex flex-col overflow-y-auto scrollbar-thin">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <FileText className="h-4 w-4 text-nominal" />
          <h2 className="font-sans text-sm font-semibold tracking-wider text-nominal text-glow-green">
            AUTO-GENERATED REPORT
          </h2>
        </div>
        {isLocked && (
          <div className="flex items-center gap-1 text-[10px] text-nominal font-bold tracking-wider">
            <Lock className="h-3 w-3" />
            TAMPER-PROOF
          </div>
        )}
      </div>

      {/* Report Preview */}
      <div className="flex-1 rounded border border-border bg-background/50 p-4 mb-4 scanline">
        <div className="space-y-4">
          <div className="text-center border-b border-border pb-3">
            <div className="flex items-center justify-center gap-2 mb-1">
              <Shield className="h-4 w-4 text-primary" />
              <span className="font-sans text-sm font-bold tracking-wider text-primary">BLACKBOX AI</span>
            </div>
            <p className="text-[10px] text-muted-foreground tracking-widest">INCIDENT REPORT</p>
          </div>

          <div className="grid grid-cols-2 gap-3 text-xs">
            <div>
              <span className="text-[9px] text-muted-foreground tracking-widest">REPORT ID</span>
              <p className="text-foreground font-mono">RPT-{incident.id.toUpperCase()}</p>
            </div>
            <div>
              <span className="text-[9px] text-muted-foreground tracking-widest">GENERATED</span>
              <p className="text-foreground font-mono">{formatDate(new Date())}</p>
            </div>
            <div>
              <span className="text-[9px] text-muted-foreground tracking-widest">INCIDENT TIME</span>
              <p className="text-foreground font-mono">{formatDate(incident.timestamp)}</p>
            </div>
            <div>
              <span className="text-[9px] text-muted-foreground tracking-widest">DURATION</span>
              <p className="text-foreground font-mono">{incident.duration}</p>
            </div>
          </div>

          <div>
            <span className="text-[9px] text-muted-foreground tracking-widest">TITLE</span>
            <p className="text-xs text-foreground font-semibold mt-0.5">{incident.title}</p>
          </div>

          <div className="rounded border border-critical/20 bg-critical/5 px-3 py-2">
            <span className="text-[9px] font-bold tracking-widest text-critical">ROOT CAUSE</span>
            <p className="text-[11px] text-foreground mt-1 leading-relaxed">{incident.rootCause}</p>
          </div>

          <div>
            <span className="text-[9px] text-muted-foreground tracking-widest">TIMELINE ({incident.timeline.length} EVENTS)</span>
            <div className="mt-1 space-y-1">
              {incident.timeline.slice(0, 4).map(e => (
                <div key={e.id} className="flex items-center gap-2 text-[11px]">
                  <span className={`font-bold tracking-wider ${
                    e.severity === 'critical' ? 'text-critical' : e.severity === 'warning' ? 'text-primary' : 'text-muted-foreground'
                  }`}>
                    [{e.severity.toUpperCase().slice(0, 4)}]
                  </span>
                  <span className="text-foreground">{e.label}</span>
                </div>
              ))}
              {incident.timeline.length > 4 && (
                <p className="text-[10px] text-muted-foreground">+ {incident.timeline.length - 4} more events</p>
              )}
            </div>
          </div>

          <div>
            <span className="text-[9px] text-muted-foreground tracking-widest">EVIDENCE ({incident.evidence.length} ITEMS)</span>
            <div className="mt-1 space-y-1">
              {incident.evidence.map(e => (
                <div key={e.id} className="text-[11px] text-secondary-foreground">
                  ▸ {e.label} ({e.unit})
                </div>
              ))}
            </div>
          </div>

          <div className="border-t border-border pt-2 text-center">
            <p className="text-[9px] text-muted-foreground tracking-widest">
              SHA256: {Math.random().toString(36).substring(2, 18).toUpperCase()}
            </p>
            <p className="text-[9px] text-muted-foreground">BlackBox AI v3.2.1 — On-Device Processing</p>
          </div>
        </div>
      </div>

      {/* Actions */}
      <div className="grid grid-cols-2 gap-2">
        <Button
          onClick={handleDownload}
          disabled={isGenerating}
          className="gap-2 text-xs"
          variant="default"
        >
          <Download className="h-3.5 w-3.5" />
          {isGenerating ? 'GENERATING...' : 'DOWNLOAD'}
        </Button>
        <Button onClick={handleCopy} variant="outline" className="gap-2 text-xs">
          <Copy className="h-3.5 w-3.5" />
          COPY SUMMARY
        </Button>
        <Button onClick={handlePrint} variant="outline" className="gap-2 text-xs">
          <Printer className="h-3.5 w-3.5" />
          PRINT
        </Button>
        <Button
          onClick={handleLock}
          disabled={isLocked}
          variant={isLocked ? 'secondary' : 'outline'}
          className="gap-2 text-xs"
        >
          <Lock className="h-3.5 w-3.5" />
          {isLocked ? 'LOCKED' : 'LOCK REPORT'}
        </Button>
      </div>
    </div>
  );
}
